### ISSUE TITLE
请问这个还能用吗?

### ISSUE THREAD

**Issue by HIjack2015** [xxxyanchenxxx/HookIME#1]

**Comment by HIjack2015** [comment]
直接使用报错如下:

`
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at com.jk.hookkeyboard.hook.InputMethodManagerServiceHandler.invoke(InputMethodManagerServiceHandler.java:41)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:913)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at $Proxy0.startInputOrWindowGainedFocus(Unknown Source)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1295)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1538)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3866)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
2019-10-15 18:06:37.737 9013-9013/com.jk.hookkeyboard W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2019-10-15 18:06:37.738 9013-9013/com.jk.hookkeyboard W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
`
